version: "3.4"

services:
  nginx:
    image: lightdance-nginx
    container_name: lightdance-nginx
    hostname: lightdance-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - nginx
    depends_on:
      - editor-server
      - file-server

  editor-server:
    image: lightdance-editor-server
    container_name: lightdance-editor-server
    build:
      context: ..
      dockerfile: ./prod-support/editor-server/Dockerfile
    networks:
      - nginx
    depends_on:
      - mysql
      - redisdb

  file-server:
    image: lightdance-file-server
    container_name: lightdance-file-server
    build:
      context: ..
      dockerfile: ./prod-support/file-server/Dockerfile
    volumes:
      - ../files:/app/files
    networks:
      - nginx

  mysql:
    image: mysql:8.1.0
    container_name: lightdance-mysql
    environment:
      MYSQL_DATABASE: editor
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nginx

  redisdb:
    image: redis
    container_name: lightdance-redisdb
    volumes:
      - redis-data:/data
    networks:
      - nginx

networks:
  nginx:
    external: true

volumes:
  mysql-data:
  redis-data:
