version: "3.4"

services:
  nginx:
    image: lightdance-nginx
    container_name: lightdance-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - lightdance-editor
    depends_on:
      - editor
      - editor-server
      - file-server

  editor:
    image: lightdance-editor
    container_name: lightdance-editor
    build:
      context: ..
      dockerfile: ./prod-support/editor/Dockerfile
    expose:
      - "8080"
    networks:
      - lightdance-editor
    depends_on:
      - editor-server
      - file-server

  editor-server:
    image: lightdance-editor-server
    container_name: lightdance-editor-server
    build:
      context: ..
      dockerfile: ./prod-support/editor-server/Dockerfile
    ports:
      - "4000:4000"
    networks:
      - lightdance-editor
    depends_on:
      - postgresql
      - redisdb

  file-server:
    image: lightdance-file-server
    container_name: lightdance-file-server
    build:
      context: ..
      dockerfile: ./prod-support/file-server/Dockerfile
    volumes:
      - ../files:/app/files
    networks:
      - lightdance-editor

  postgresql:
    image: postgres
    container_name: lightdance-postgresql
    environment:
      POSTGRES_DB: lightdance
      POSTGRES_USER: lightdance-user
      POSTGRES_PASSWORD: NTUEELightdance
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - lightdance-editor
    expose:
      - 5432

  redisdb:
    container_name: lightdance-redisdb
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - lightdance-editor

networks:
  lightdance-editor:
    external: true
    name: eeinfo

volumes:
  pg-data:
  redis-data:
