name: eslint no fail
run-name: ${{ github.actor }} is enforcing coding style
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: enable pnpm
        run: corepack enable
      - name: Install modules
        run: pnpm run install-pnpm:all
        continue-on-error: true
      - name: Run ESLint for all packages
        run: pnpm run lint:all
        continue-on-error: true
