name: eslint no fail
run-name: eslint no fail ${{ github.event.pull_request.branches[0].name }}
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: enable pnpm
        run: corepack enable
      - name: Install modules in controller-server
        run: pnpm --dir controller-server install
      - name: Run ESLint for controller-server
        run: pnpm --dir controller-server lint
        continue-on-error: true
